version: "3.1"

services:
  ks_embedding_api:
    image: ks-embedding-api:latest
    container_name: ks_embedding_api
    environment:
      - FLASK_APP=src/main.py
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
    ports:
      - "5000:5000"
    networks:
      - network

networks:
  network:
    driver: bridge
